/**
 * Icon registry: kebab-case names (as in the design's `ph-*` classes) → Phosphor SVG components.
 * Uses the SSR entry so icons render in both server and client components.
 * Add an icon here before using it; `IconName` makes unknown names a compile error.
 */
import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import {
  ArrowBendLeftUpIcon,
  ArrowBendUpRightIcon,
  ArrowLeftIcon,
  ArrowUpRightIcon,
  ArrowsClockwiseIcon,
  ArrowsDownUpIcon,
  ArrowsOutCardinalIcon,
  BroomIcon,
  BugIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  ChartLineUpIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckSquareIcon,
  CircleIcon,
  CircleNotchIcon,
  CloudArrowUpIcon,
  CopyIcon,
  CornersOutIcon,
  CpuIcon,
  DatabaseIcon,
  DesktopIcon,
  DeviceMobileIcon,
  DeviceTabletIcon,
  DevicesIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FileIcon,
  FileAudioIcon,
  FileImageIcon,
  FileVideoIcon,
  FileXIcon,
  FileZipIcon,
  FilmStripIcon,
  FireIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FolderSimpleIcon,
  FolderSimplePlusIcon,
  GaugeIcon,
  GearSixIcon,
  GlobeSimpleIcon,
  HardDrivesIcon,
  HashIcon,
  HourglassMediumIcon,
  HourglassSimpleLowIcon,
  HouseIcon,
  IdentificationCardIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  KeyboardIcon,
  LinkBreakIcon,
  LinkSimpleIcon,
  ListIcon,
  ListBulletsIcon,
  LockKeyIcon,
  LockSimpleIcon,
  MagnifyingGlassIcon,
  MegaphoneIcon,
  MemoryIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  NoteIcon,
  PaletteIcon,
  PaperPlaneTiltIcon,
  PauseIcon,
  PauseCircleIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlayCircleIcon,
  PlusIcon,
  ProhibitIcon,
  PulseIcon,
  RadioButtonIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  SignInIcon,
  SignOutIcon,
  SkipForwardIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  SquareIcon,
  SquaresFourIcon,
  SwapIcon,
  TagIcon,
  TimerIcon,
  TrafficSignalIcon,
  TrashIcon,
  UploadSimpleIcon,
  UserIcon,
  UserCirclePlusIcon,
  UsersThreeIcon,
  WarningIcon,
  WarningCircleIcon,
  WarningOctagonIcon,
  WifiSlashIcon,
  WrenchIcon,
  XIcon,
  XCircleIcon,
} from "@phosphor-icons/react/ssr";

export const ICONS = {
  "arrow-bend-left-up": ArrowBendLeftUpIcon,
  "arrow-bend-up-right": ArrowBendUpRightIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-up-right": ArrowUpRightIcon,
  "arrows-clockwise": ArrowsClockwiseIcon,
  "arrows-down-up": ArrowsDownUpIcon,
  "arrows-out-cardinal": ArrowsOutCardinalIcon,
  "broom": BroomIcon,
  "bug": BugIcon,
  "calendar-blank": CalendarBlankIcon,
  "calendar-check": CalendarCheckIcon,
  "caret-down": CaretDownIcon,
  "caret-left": CaretLeftIcon,
  "caret-right": CaretRightIcon,
  "caret-up": CaretUpIcon,
  "chart-line-up": ChartLineUpIcon,
  "check": CheckIcon,
  "check-circle": CheckCircleIcon,
  "check-square": CheckSquareIcon,
  "circle": CircleIcon,
  "circle-notch": CircleNotchIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  "copy": CopyIcon,
  "corners-out": CornersOutIcon,
  "cpu": CpuIcon,
  "database": DatabaseIcon,
  "desktop": DesktopIcon,
  "device-mobile": DeviceMobileIcon,
  "device-tablet": DeviceTabletIcon,
  "devices": DevicesIcon,
  "dots-three-vertical": DotsThreeVerticalIcon,
  "download-simple": DownloadSimpleIcon,
  "eye": EyeIcon,
  "eye-slash": EyeSlashIcon,
  "file": FileIcon,
  "file-audio": FileAudioIcon,
  "file-image": FileImageIcon,
  "file-video": FileVideoIcon,
  "file-x": FileXIcon,
  "file-zip": FileZipIcon,
  "film-strip": FilmStripIcon,
  "fire": FireIcon,
  "folder-open": FolderOpenIcon,
  "folder-plus": FolderPlusIcon,
  "folder-simple": FolderSimpleIcon,
  "folder-simple-plus": FolderSimplePlusIcon,
  "gauge": GaugeIcon,
  "gear-six": GearSixIcon,
  "globe-simple": GlobeSimpleIcon,
  "hard-drives": HardDrivesIcon,
  "hash": HashIcon,
  "hourglass-medium": HourglassMediumIcon,
  "hourglass-simple-low": HourglassSimpleLowIcon,
  "house": HouseIcon,
  "identification-card": IdentificationCardIcon,
  "image": ImageIcon,
  "info": InfoIcon,
  "key": KeyIcon,
  "keyboard": KeyboardIcon,
  "link-break": LinkBreakIcon,
  "link-simple": LinkSimpleIcon,
  "list": ListIcon,
  "list-bullets": ListBulletsIcon,
  "lock-key": LockKeyIcon,
  "lock-simple": LockSimpleIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  "megaphone": MegaphoneIcon,
  "memory": MemoryIcon,
  "music-note": MusicNoteIcon,
  "music-notes": MusicNotesIcon,
  "note": NoteIcon,
  "palette": PaletteIcon,
  "paper-plane-tilt": PaperPlaneTiltIcon,
  "pause": PauseIcon,
  "pause-circle": PauseCircleIcon,
  "pencil-simple": PencilSimpleIcon,
  "play": PlayIcon,
  "play-circle": PlayCircleIcon,
  "plus": PlusIcon,
  "prohibit": ProhibitIcon,
  "pulse": PulseIcon,
  "radio-button": RadioButtonIcon,
  "share-network": ShareNetworkIcon,
  "shield-check": ShieldCheckIcon,
  "shield-warning": ShieldWarningIcon,
  "sign-in": SignInIcon,
  "sign-out": SignOutIcon,
  "skip-forward": SkipForwardIcon,
  "sliders-horizontal": SlidersHorizontalIcon,
  "sparkle": SparkleIcon,
  "square": SquareIcon,
  "squares-four": SquaresFourIcon,
  "swap": SwapIcon,
  "tag": TagIcon,
  "timer": TimerIcon,
  "traffic-signal": TrafficSignalIcon,
  "trash": TrashIcon,
  "upload-simple": UploadSimpleIcon,
  "user": UserIcon,
  "user-circle-plus": UserCirclePlusIcon,
  "users-three": UsersThreeIcon,
  "warning": WarningIcon,
  "warning-circle": WarningCircleIcon,
  "warning-octagon": WarningOctagonIcon,
  "wifi-slash": WifiSlashIcon,
  "wrench": WrenchIcon,
  "x": XIcon,
  "x-circle": XCircleIcon,
} as const satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

export function isIconName(value: string): value is IconName {
  return Object.hasOwn(ICONS, value);
}
