#!/usr/bin/env node
/**
 * Prints freshly generated secret values for .env. Nothing is written to disk:
 * copy the lines you need into your .env file.
 */
import { randomBytes } from "node:crypto";

const alnum = (bytes) => randomBytes(bytes).toString("base64url");

const values = {
  POSTGRES_PASSWORD: alnum(24),
  REDIS_PASSWORD: alnum(24),
  TOKEN_ENC_KEY: randomBytes(32).toString("base64"),
  TOKEN_HMAC_KEY: alnum(48),
  COOKIE_SECRET: alnum(48),
};

console.log("# Generated by npm run env:secrets — paste into .env (do not commit)");
for (const [key, value] of Object.entries(values)) console.log(`${key}=${value}`);
